project:
  title: "Primordial Machine"
  type: website
  output-dir: .render

website:
  title: "Primordial Machine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "https://develop.primordialmachine.com/forums/"
        target: "_blank"
        text: Forum
      - href: documentation/ddl-specification/index.qmd
        text: "DDL Specification"
      - href: documentation/adl-specification/index.qmd
        text: "ADL Specification"
      - about.qmd

format:
  html:
    theme: cosmo