#if !defined(DX_CONFIGURATION_H_INCLUDED)
#define DX_CONFIGURATION_H_INCLUDED

#define DX_CONFIGURATION_VISUALS_DIRECT3D (1)

#define DX_CONFIGURATION_VISUALS_OPENGL (2)

#define DX_CONFIGURATION_VISUALS_VULKAN3D (3)

#define DX_CONFIGURATION_VISUALS DX_CONFIGURATION_VISUALS_OPENGL

#endif // DX_CONFIGURATION_H_INCLUDED
